### ISSUE TITLE
moving to cloudmesh-flow

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-flow#10]
The way we do this is simply to rename and move this repor, and create a new one.
Is there a time wher you both can be on zoom so we can coordinnate this? Evenings is fine for this as important. I want to make sure that this is done smoothly shodl take only 5-10 minutes 

So do not yet commit to:
https://github.com/cloudmesh/cloudmesh-flow

for now as the method i have in mind is far simpler

**Comment by hrbahramian** [comment]
I am available anytime on Wednesday and Thursday. 

Thanks,

Hamid

**Comment by laszewsk** [comment]
please let me know time and i can be there

**Comment by robludwig** [comment]
Thursday Apr 25 at 12:15

**Comment by hrbahramian** [comment]
I'll join your zoom meeting on Thursday Apr 25 at 12:15.

**Comment by robludwig** [comment]
successfully moved
