### ISSUE TITLE
status missing inmongo objects

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-flow#15]
the mongo objects needs a status

"status": "running"
"status": "defined"
"status": "ready"
"status": "error"
"status": "done"

**Comment by robludwig** [comment]
The current implementation has status only on workflows that are running. This is after our discussion that it should be possible to run a workflow multiple times. So when a workflow is created it has no status, but when it is _activated_ it creates a new workflow with a name like "x-flow-active", and that has a status like "pending", "running", "done"

**Comment by laszewsk** [comment]
you could add a default status such as defined

**Comment by robludwig** [comment]
Default status is "defined". 

When a workflow is running, all nodes are upgraded to status "pending". When the executor selects & starts a node, it becomes "running".

From there, it can transition to "error" or "finished"

**Comment by hrbahramian** [comment]
In the visualize package, status is color-coded as the following:

        color = 'violet'
        if task.status == "pending":
            color = 'lightblue'
        elif task.status == "running":
            color = 'orange'
        elif task.status == "error":
            color = 'red'
        elif task.status == "finished":
            color = 'green'
