### ISSUE TITLE
Lecture Log

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-flow#4]
BOOK_516
- [ ]  [SECTION-PREFACE](https://github.com/cloudmesh-community/book/blob/master/SECTION-PREFACE.md)
    - [ ]  [reader](https://github.com/cloudmesh-community/book/blob/master/chapters/preface/reader.md)
    - [ ]  [corrections](https://github.com/cloudmesh-community/book/blob/master/chapters/preface/corrections.md)
    - [ ]  [authors](https://github.com/cloudmesh-community/book/blob/master/chapters/authors.md)
    - [ ]  [create](https://github.com/cloudmesh-community/book/blob/master/chapters/preface/create.md)
    - [ ]  [notation](https://github.com/cloudmesh-community/book/blob/master/chapters/preface/notation.md)
    - [ ]  [updates](https://github.com/cloudmesh-community/book/blob/master/chapters/updates.md)
    - [ ]  [516-week](https://github.com/cloudmesh-community/book/blob/master/chapters/class/516-week.md)
- [ ]  [SECTION-QUICK516](https://github.com/cloudmesh-community/book/blob/master/SECTION-QUICK516.md)
    - [ ]  [quick516](https://github.com/cloudmesh-community/book/blob/master/chapters/quick516.md)
    - [ ]  [assignment](https://github.com/cloudmesh-community/book/blob/master/chapters/assignment.md)
    - [ ]  [e516-syllabus-table](https://github.com/cloudmesh-community/book/blob/master/chapters/class/e516-syllabus-table.md)
- [ ]  [SECTION-OVERVIEW](https://github.com/cloudmesh-community/book/blob/master/SECTION-OVERVIEW.md)
    - [ ]  [organization-516](https://github.com/cloudmesh-community/book/blob/master/chapters/class/organization-516.md)
    - [ ]  [plagiarism](https://github.com/cloudmesh-community/book/blob/master/chapters/class/plagiarism.md)
    - [ ]  [gregor](https://github.com/cloudmesh-community/book/blob/master/chapters/cloud/gregor.md)
    - [ ]  [e516-engineering-cloud-computing](https://github.com/cloudmesh-community/book/blob/master/chapters/class/e516-engineering-cloud-computing.md)
    - [ ]  [policies](https://github.com/cloudmesh-community/book/blob/master/chapters/class/policies.md)
    - [ ]  [e516-summary](https://github.com/cloudmesh-community/book/blob/master/chapters/class/e516-summary.md)
    - [ ]  [volumes](https://github.com/cloudmesh-community/book/blob/master/chapters/class/volumes.md)
- [ ]  [e516-definition](https://github.com/cloudmesh-community/book/blob/master/chapters/class/e516-definition.md)
- [ ]  [datacenter](https://github.com/cloudmesh-community/book/blob/master/chapters/cloud/datacenter.md)
- [ ]  [arch](https://github.com/cloudmesh-community/book/blob/master/chapters/arch.md)
- [ ]  [bdra](https://github.com/cloudmesh-community/book/blob/master/chapters/nist/bdra.md)
- [ ]  [rest](https://github.com/cloudmesh-community/book/blob/master/chapters/rest/rest.md)
    - [ ]  [swagger](https://github.com/cloudmesh-community/book/blob/master/chapters/rest/swagger.md)
    - [ ]  [swagger-spec](https://github.com/cloudmesh-community/book/blob/master/chapters/rest/swagger-spec.md)
    - [ ]  [swagger-introspection](https://github.com/cloudmesh-community/book/blob/master/chapters/rest/swagger-introspection.md)
    - [ ]  [swagger-codegen](https://github.com/cloudmesh-community/book/blob/master/chapters/rest/swagger-codegen.md)
    - [ ]  [github](https://github.com/cloudmesh-community/book/blob/master/chapters/prg/github.md)
- [ ]  [virtualization](https://github.com/cloudmesh-community/book/blob/master/chapters/cloud/virtualization.md)
    - [ ]  [qemu](https://github.com/cloudmesh-community/book/blob/master/chapters/cloud/qemu.md)
    - [ ]  [virsh](https://github.com/cloudmesh-community/book/blob/master/chapters/cloud/virsh.md)
- [ ]  [SECTION-IAAS](https://github.com/cloudmesh-community/book/blob/master/SECTION-IAAS.md)
    - [ ]  [iaas](https://github.com/cloudmesh-community/book/blob/master/chapters/iaas/iaas.md)
    - [ ]  [aws](https://github.com/cloudmesh-community/book/blob/master/chapters/iaas/aws/aws.md)
    - [ ]  [azure](https://github.com/cloudmesh-community/book/blob/master/chapters/iaas/azure/azure.md)
    - [ ]  [watson](https://github.com/cloudmesh-community/book/blob/master/chapters/iaas/watson/watson.md)
    - [ ]  [gcloud](https://github.com/cloudmesh-community/book/blob/master/chapters/iaas/gcloud/gcloud.md)
    - [ ]  [openstack](https://github.com/cloudmesh-community/book/blob/master/chapters/iaas/openstack/openstack.md)
    - [ ]  [libcloud](https://github.com/cloudmesh-community/book/blob/master/chapters/iaas/libcloud.md)
    - [ ]  [boto](https://github.com/cloudmesh-community/book/blob/master/chapters/iaas/boto.md)
- [ ]  [SECTION-MAPREDUCE](https://github.com/cloudmesh-community/book/blob/master/SECTION-MAPREDUCE.md)
    - [ ]  [mapreduce](https://github.com/cloudmesh-community/book/blob/master/chapters/mapreduce/mapreduce.md)
    - [ ]  [hadoop-lectures](https://github.com/cloudmesh-community/book/blob/master/chapters/mapreduce/hadoop-lectures.md)
        - [ ]  [hadoop-installation](https://github.com/cloudmesh-community/book/blob/master/chapters/mapreduce/hadoop-installation.md)
    - [ ]  [SECTION-SPARK](https://github.com/cloudmesh-community/book/blob/master/SECTION-SPARK.md)
        - [ ]  [spark-lectures](https://github.com/cloudmesh-community/book/blob/master/chapters/mapreduce/spark-lectures.md)
        - [ ]  [spark-installation](https://github.com/cloudmesh-community/book/blob/master/chapters/mapreduce/spark-installation.md)
        - [ ]  [spark-streaming](https://github.com/cloudmesh-community/book/blob/master/chapters/mapreduce/spark-streaming.md)
        - [ ]  [spark-udf](https://github.com/cloudmesh-community/book/blob/master/chapters/mapreduce/spark-udf.md)
    - [ ]  [SECTION-HADOOP-ADVANCED](https://github.com/cloudmesh-community/book/blob/master/SECTION-HADOOP-ADVANCED.md)
        - [ ]  [amazon-emr-1](https://github.com/cloudmesh-community/book/blob/master/chapters/mapreduce/amazon-emr-1.md)
        - [ ]  [hadoop-rdma](https://github.com/cloudmesh-community/book/blob/master/chapters/mapreduce/hadoop-rdma.md)
- [ ]  [SECTION-CONTAINER](https://github.com/cloudmesh-community/book/blob/master/SECTION-CONTAINER.md)
    - [ ]  [container](https://github.com/cloudmesh-community/book/blob/master/chapters/container/container.md)
    - [ ]  [SECTION-DOCKER](https://github.com/cloudmesh-community/book/blob/master/SECTION-DOCKER.md)
        - [ ]  [docker-intro](https://github.com/cloudmesh-community/book/blob/master/chapters/container/docker-intro.md)
        - [ ]  [docker-local](https://github.com/cloudmesh-community/book/blob/master/chapters/container/docker-local.md)
        - [ ]  [dockerfile](https://github.com/cloudmesh-community/book/blob/master/chapters/container/dockerfile.md)
        - [ ]  [dockerhub](https://github.com/cloudmesh-community/book/blob/master/chapters/container/dockerhub.md)
    - [ ]  [SECTION-DOCKER-PAAS](https://github.com/cloudmesh-community/book/blob/master/SECTION-DOCKER-PAAS.md)
        - [ ]  [docker-swarm](https://github.com/cloudmesh-community/book/blob/master/chapters/container/docker-swarm.md)
        - [ ]  [docker-fs](https://github.com/cloudmesh-community/book/blob/master/chapters/container/docker-fs.md)
        - [ ]  [docker-hadoop](https://github.com/cloudmesh-community/book/blob/master/chapters/container/docker-hadoop.md)
        - [ ]  [docker-pagerank-example-instruction](https://github.com/cloudmesh-community/book/blob/master/chapters/container/docker-pagerank-example-instruction.md)
        - [ ]  [docker-spark](https://github.com/cloudmesh-community/book/blob/master/chapters/container/docker-spark.md)
    - [ ]  [SECTION-KUBERNETES](https://github.com/cloudmesh-community/book/blob/master/SECTION-KUBERNETES.md)
        - [ ]  [kubernetes-intro](https://github.com/cloudmesh-community/book/blob/master/chapters/container/kubernetes-intro.md)
        - [ ]  [kubernetes-fs](https://github.com/cloudmesh-community/book/blob/master/chapters/container/kubernetes-fs.md)
    - [ ]  [singularity](https://github.com/cloudmesh-community/book/blob/master/chapters/container/singularity/singularity.md)
    - [ ]  [exercise](https://github.com/cloudmesh-community/book/blob/master/chapters/container/exercise.md)
- [ ]  [SECTION-SERVERLESS](https://github.com/cloudmesh-community/book/blob/master/SECTION-SERVERLESS.md)
    - [ ]  [introduction](https://github.com/cloudmesh-community/book/blob/master/chapters/faas/introduction.md)
    - [ ]  [aws-lambda](https://github.com/cloudmesh-community/book/blob/master/chapters/faas/aws-lambda.md)
    - [ ]  [openwhisk](https://github.com/cloudmesh-community/book/blob/master/chapters/faas/openwhisk.md)
    - [ ]  [kubeless](https://github.com/cloudmesh-community/book/blob/master/chapters/faas/kubeless.md)
    - [ ]  [microsoft-azure-functions](https://github.com/cloudmesh-community/book/blob/master/chapters/faas/microsoft-azure-functions.md)
    - [ ]  [google-cloud-functions](https://github.com/cloudmesh-community/book/blob/master/chapters/faas/google-cloud-functions.md)
    - [ ]  [openfaas](https://github.com/cloudmesh-community/book/blob/master/chapters/faas/openfaas.md)
    - [ ]  [riff](https://github.com/cloudmesh-community/book/blob/master/chapters/faas/riff.md)
    - [ ]  [fission](https://github.com/cloudmesh-community/book/blob/master/chapters/faas/fission.md)
    - [ ]  [ironfunction](https://github.com/cloudmesh-community/book/blob/master/chapters/faas/ironfunction.md)
    - [ ]  [fn](https://github.com/cloudmesh-community/book/blob/master/chapters/faas/fn.md)
    - [ ]  [gestalt](https://github.com/cloudmesh-community/book/blob/master/chapters/faas/gestalt.md)
    - [ ]  [openlambda](https://github.com/cloudmesh-community/book/blob/master/chapters/faas/openlambda.md)
    - [ ]  [spring-cloud-function](https://github.com/cloudmesh-community/book/blob/master/chapters/faas/spring-cloud-function.md)
- [ ]  [SECTION-DEVTOOLS](https://github.com/cloudmesh-community/book/blob/master/SECTION-DEVTOOLS.md)
    - [ ]  [refcards](https://github.com/cloudmesh-community/book/blob/master/chapters/linux/refcards.md)
    - [ ]  [virtualbox](https://github.com/cloudmesh-community/book/blob/master/chapters/cloud/virtualbox.md)
    - [ ]  [vagrant](https://github.com/cloudmesh-community/book/blob/master/chapters/cloud/vagrant.md)
    - [ ]  [packer](https://github.com/cloudmesh-community/book/blob/master/chapters/cloud/packer.md)
    - [ ]  [ubuntu-usb-osx](https://github.com/cloudmesh-community/book/blob/master/chapters/os/ubuntu-usb-osx.md)
    - [ ]  [github](https://github.com/cloudmesh-community/book/blob/master/chapters/git/github.md)
        - [ ]  [gitpullreqest](https://github.com/cloudmesh-community/book/blob/master/chapters/git/gitpullreqest.md)
    - [ ]  [linux](https://github.com/cloudmesh-community/book/blob/master/chapters/linux/linux.md)
    - [ ]  [ssh](https://github.com/cloudmesh-community/book/blob/master/chapters/linux/ssh.md)
    - [ ]  [ssh-futuresystems](https://github.com/cloudmesh-community/book/blob/master/chapters/linux/ssh-futuresystems.md)
    - [ ]  [ssh-excerise](https://github.com/cloudmesh-community/book/blob/master/chapters/linux/ssh-excerise.md)
- [ ]  [SECTION-PYTHON](https://github.com/cloudmesh-community/book/blob/master/chapters/prg/SECTION-PYTHON.md)
    - [ ]  [python-intro](https://github.com/cloudmesh-community/book/blob/master/chapters/prg/python/python-intro.md)
    - [ ]  [python-install](https://github.com/cloudmesh-community/book/blob/master/chapters/prg/python/python-install.md)
    - [ ]  [python-interactive](https://github.com/cloudmesh-community/book/blob/master/chapters/prg/python/python-interactive.md)
    - [ ]  [python-editor](https://github.com/cloudmesh-community/book/blob/master/chapters/prg/python/python-editor.md)
    - [ ]  [python](https://github.com/cloudmesh-community/book/blob/master/chapters/prg/python/python.md)
    - [ ]  [python-libraries](https://github.com/cloudmesh-community/book/blob/master/chapters/prg/python/python-libraries.md)
        - [ ]  [python-data](https://github.com/cloudmesh-community/book/blob/master/chapters/prg/python/python-data.md)
        - [ ]  [python-matplotlib](https://github.com/cloudmesh-community/book/blob/master/chapters/prg/python/python-matplotlib.md)
        - [ ]  [python-docopts](https://github.com/cloudmesh-community/book/blob/master/chapters/prg/python/python-docopts.md)
    - [ ]  [SECTION-DATA](https://github.com/cloudmesh-community/book/blob/master/SECTION-DATA.md)
        - [ ]  [formats](https://github.com/cloudmesh-community/book/blob/master/chapters/data/formats.md)
    - [ ]  [mongodb](https://github.com/cloudmesh-community/book/blob/master/chapters/data/mongodb.md)
        - [ ]  [mongoengine](https://github.com/cloudmesh-community/book/blob/master/chapters/data/mongoengine.md)
    - [ ]  [python-wordcount](https://github.com/cloudmesh-community/book/blob/master/chapters/prg/python/python-wordcount.md)
- [ ]  [go-intro](https://github.com/cloudmesh-community/book/blob/master/chapters/prg/go/go-intro.md)
    - [ ]  [go-install](https://github.com/cloudmesh-community/book/blob/master/chapters/prg/go/go-install.md)
    - [ ]  [go-editor](https://github.com/cloudmesh-community/book/blob/master/chapters/prg/go/go-editor.md)
    - [ ]  [go-language](https://github.com/cloudmesh-community/book/blob/master/chapters/prg/go/go-language.md)
    - [ ]  [go-libraries](https://github.com/cloudmesh-community/book/blob/master/chapters/prg/go/go-libraries.md)
    - [ ]  [go-cmd](https://github.com/cloudmesh-community/book/blob/master/chapters/prg/go/go-cmd.md)
    - [ ]  [go-rest](https://github.com/cloudmesh-community/book/blob/master/chapters/prg/go/go-rest.md)
    - [ ]  [go-openapi](https://github.com/cloudmesh-community/book/blob/master/chapters/prg/go/go-openapi.md)
    - [ ]  [go-cloud](https://github.com/cloudmesh-community/book/blob/master/chapters/prg/go/go-cloud.md)
    - [ ]  [go-links](https://github.com/cloudmesh-community/book/blob/master/chapters/prg/go/go-links.md)
- [ ]  [MSG](https://github.com/cloudmesh-community/book/blob/master/chapters/MSG.md)
    - [ ]  [mqtt](https://github.com/cloudmesh-community/book/blob/master/chapters/msg/mqtt.md)
    - [ ]  [graphql](https://github.com/cloudmesh-community/book/blob/master/chapters/msg/graphql.md)
    - [ ]  [avro](https://github.com/cloudmesh-community/book/blob/master/chapters/msg/avro.md)
    - [ ]  [flink](https://github.com/cloudmesh-community/book/blob/master/chapters/msg/flink.md)
- [ ]  [SECTION-FAQ](https://github.com/cloudmesh-community/book/blob/master/SECTION-FAQ.md)
    - [ ]  [faq](https://github.com/cloudmesh-community/book/blob/master/chapters/faq.md)
    - [ ]  [faq-516](https://github.com/cloudmesh-community/book/blob/master/chapters/faq-516.md)
- [ ]  [SECTION-APPENDIX](https://github.com/cloudmesh-community/book/blob/master/SECTION-APPENDIX.md)
    - [ ]  [products](https://github.com/cloudmesh-community/book/blob/master/chapters/iaas/aws/products.md)
    - [ ]  [products](https://github.com/cloudmesh-community/book/blob/master/chapters/iaas/azure/products.md)
- [ ]  [futuresystems](https://github.com/cloudmesh-community/book/blob/master/chapters/iaas/futuresystems/futuresystems.md)
- [ ]  [SECTION-CHAMELEON](https://github.com/cloudmesh-community/book/blob/master/SECTION-CHAMELEON.md)
    - [ ]  [resources](https://github.com/cloudmesh-community/book/blob/master/chapters/cloud/chameleon/resources.md)
    - [ ]  [hardware](https://github.com/cloudmesh-community/book/blob/master/chapters/cloud/chameleon/hardware.md)
    - [ ]  [charge](https://github.com/cloudmesh-community/book/blob/master/chapters/cloud/chameleon/charge.md)
    - [ ]  [start](https://github.com/cloudmesh-community/book/blob/master/chapters/cloud/chameleon/start.md)
    - [ ]  [user-guide](https://github.com/cloudmesh-community/book/blob/master/chapters/cloud/chameleon/user-guide.md)
    - [ ]  [cli](https://github.com/cloudmesh-community/book/blob/master/chapters/cloud/chameleon/cli.md)
    - [ ]  [horizon](https://github.com/cloudmesh-community/book/blob/master/chapters/cloud/chameleon/horizon.md)
    - [ ]  [heat](https://github.com/cloudmesh-community/book/blob/master/chapters/cloud/chameleon/heat.md)
    - [ ]  [baremetal](https://github.com/cloudmesh-community/book/blob/master/chapters/cloud/chameleon/baremetal.md)
    - [ ]  [faq](https://github.com/cloudmesh-community/book/blob/master/chapters/cloud/chameleon/faq.md)
- [ ]  [glossary](https://github.com/cloudmesh-community/book/blob/master/chapters/container/glossary.md)
- [ ]  [SECTION-INCOMING](https://github.com/cloudmesh-community/book/blob/master/SECTION-INCOMING.md)
    - [ ]  [box](https://github.com/cloudmesh-community/book/blob/master/chapters/in/box.md)
    - [ ]  [aws-auroradb](https://github.com/cloudmesh-community/book/blob/master/chapters/in/aws-auroradb.md)
    - [ ]  [aws-documentdb](https://github.com/cloudmesh-community/book/blob/master/chapters/in/aws-documentdb.md)
    - [ ]  [aws-elasticbeanstalk](https://github.com/cloudmesh-community/book/blob/master/chapters/in/aws-elasticbeanstalk.md)
    - [ ]  [compliance](https://github.com/cloudmesh-community/book/blob/master/chapters/in/compliance.md)
    - [ ]  [vis](https://github.com/cloudmesh-community/book/blob/master/chapters/in/vis.md)
    - [ ]  [windows-subsystem-for-linux](https://github.com/cloudmesh-community/book/blob/master/chapters/in/windows-subsystem-for-linux.md)
- [ ]  [SECTION-INDEX](https://github.com/cloudmesh-community/book/blob/master/SECTION-INDEX.md)
    - [ ]  [index](https://github.com/cloudmesh-community/book/blob/master/chapters/index.md)
- [ ]  [SECTION-REFERENCES](https://github.com/cloudmesh-community/book/blob/master/SECTION-REFERENCES.md)

**Comment by robludwig** [comment]
@laszewsk should we move this to my personal repo? it transitioned with the project repo

**Comment by laszewsk** [comment]
yes move to personal hid repo

**Comment by robludwig** [comment]
moved to personal
