### ISSUE TITLE
finding methods

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-flow#8]
simply put the flow in a class

class MyFlow ...
def a...
def b ...
dev c ...

than use the following. you could also put a decorator on the functions, but i think this is eaier

https://stackoverflow.com/questions/1911281/how-do-i-get-list-of-methods-in-a-python-class

**Comment by laszewsk** [comment]
dir(ClassName) ?

**Comment by robludwig** [comment]
Fixed in latest
